# Generated by Django 5.2 on 2025-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alamat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_hp',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meja',
            name='status',
            field=models.CharField(choices=[('kosong', 'kosong'), ('dipesan', 'dipesan'), ('terisi', 'terisi')], max_length=10),
        ),
    ]
