# Generated by Django 5.2 on 2025-04-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0002_rename_role_customuser_status_customuser_alamat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
