# Generated by Django 5.2 on 2025-04-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meja',
            name='image_meja',
        ),
    ]
