# Generated by Django 5.2 on 2025-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0004_remove_meja_image_meja'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'pending'), ('deny', 'deny'), ('cancel', 'cancel'), ('settlement', 'settlement'), ('expired', 'expired'), ('refund', 'refund')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(max_length=20),
        ),
    ]
