# Generated by Django 5.2 on 2025-04-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0006_alter_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status_transaksi',
            field=models.CharField(choices=[('pending', 'pending'), ('reserved', 'reserved'), ('checkin', 'checkin'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
