# Generated by Django 5.2 on 2025-04-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoranApp', '0007_paymentlog_alter_transaksi_status_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meja',
            name='status',
            field=models.CharField(choices=[('kosong', 'kosong'), ('dipesan', 'dipesan'), ('terisi', 'terisi')], default='kosong', max_length=10),
        ),
    ]
